<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'dependency_injection.config.container_parameters_resource_checker' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/config/ResourceCheckerInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/Config/ContainerParametersResourceChecker.php';

return $this->services['dependency_injection.config.container_parameters_resource_checker'] = new \Symfony\Component\DependencyInjection\Config\ContainerParametersResourceChecker($this);
