<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'translation.extractor' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/translation/Extractor/ExtractorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/translation/Extractor/ChainExtractor.php';
include_once $this->targetDirs[3].'/vendor/symfony/translation/Extractor/AbstractFileExtractor.php';
include_once $this->targetDirs[3].'/vendor/symfony/translation/Extractor/PhpExtractor.php';

$this->services['translation.extractor'] = $instance = new \Symfony\Component\Translation\Extractor\ChainExtractor();

$instance->addExtractor('php', ${($_ = isset($this->services['translation.extractor.php']) ? $this->services['translation.extractor.php'] : $this->services['translation.extractor.php'] = new \Symfony\Component\Translation\Extractor\PhpExtractor()) && false ?: '_'});

return $instance;
