<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/TemplateController.php';

return $this->services['Symfony\Bundle\FrameworkBundle\Controller\TemplateController'] = new \Symfony\Bundle\FrameworkBundle\Controller\TemplateController(NULL, NULL);
