<?php
namespace FacturaScripts\Core\Base;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-24 at 16:53:33.
 */
class CacheTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Cache
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Cache();
        $this->object->clear();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers \FacturaScripts\Core\Base\Cache::get
     */
    public function testGet()
    {
        $this->object->set('TEST', 1234);
        $data = $this->object->get('TEST');
        $this->assertEquals(1234, $data);
    }

    /**
     * @covers \FacturaScripts\Core\Base\Cache::delete
     */
    public function testDelete()
    {
        $this->object->set('TEST', 1234);
        $this->object->delete('TEST');
        $this->assertEmpty($this->object->get('TEST'));
    }

    /**
     * @covers \FacturaScripts\Core\Base\Cache::clear
     */
    public function testClear()
    {
        $this->object->set('TEST_1', 12345);
        $this->object->clear();
        $this->assertEmpty($this->object->get('TEST_1'));
    }
}
