<?php
namespace FacturaScripts\Core\Base;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-24 at 16:46:47.
 */
class DefaultItemsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var DefaultItems
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DefaultItems();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers \FacturaScripts\Core\Base\DefaultItems::codEjercicio
     */
    public function testCodEjercicio()
    {
        $this->object->setCodEjercicio(1);
        $data = $this->object->codEjercicio();
        $this->assertEquals(1, $data);
    }

    /**
     * @covers \FacturaScripts\Core\Base\DefaultItems::codAlmacen
     */
    public function testCodAlmacen()
    {
        $this->object->setCodAlmacen(1);
        $data = $this->object->codAlmacen();
        $this->assertEquals(1, $data);
    }

    /**
     * @covers \FacturaScripts\Core\Base\DefaultItems::codDivisa
     */
    public function testCodDivisa()
    {
        $this->object->setCodDivisa(1);
        $data = $this->object->codDivisa();
        $this->assertEquals(1, $data);
    }

    /**
     * @covers \FacturaScripts\Core\Base\DefaultItems::codPago
     */
    public function testCodPago()
    {
        $this->object->setCodPago(1);
        $data = $this->object->codPago();
        $this->assertEquals(1, $data);
    }

    /**
     * @covers \FacturaScripts\Core\Base\DefaultItems::codImpuesto
     */
    public function testCodImpuesto()
    {
        $this->object->setCodImpuesto(1);
        $data = $this->object->codImpuesto();
        $this->assertEquals(1, $data);
    }

    /**
     * @covers \FacturaScripts\Core\Base\DefaultItems::codPais
     */
    public function testCodPais()
    {
        $this->object->setCodPais(1);
        $data = $this->object->codPais();
        $this->assertEquals(1, $data);
    }

    /**
     * @covers \FacturaScripts\Core\Base\DefaultItems::codSerie
     */
    public function testCodSerie()
    {
        $this->object->setCodSerie(1);
        $data = $this->object->codSerie();
        $this->assertEquals(1, $data);
    }

    /**
     * @covers \FacturaScripts\Core\Base\DefaultItems::defaultPage
     */
    public function testDefaultPage()
    {
        $this->object->setDefaultPage('principal');
        $data = $this->object->defaultPage();
        $this->assertEquals('principal', $data);
    }

    /**
     * @covers \FacturaScripts\Core\Base\DefaultItems::showingPage
     */
    public function testShowingPage()
    {
        $this->object->setShowingPage('default');
        $data = $this->object->showingPage();
        $this->assertEquals('default', $data);
    }
}
