<?php

namespace FacturaScripts\Core\Base;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-20 at 11:48:14.
 */
class IPFilterTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var IPFilter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IPFilter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers FacturaScripts\Core\Base\IPFilter::setAttempt
     * @todo   Implement testSetAttempt().
     */
    public function testSetAttempt() {
        // Remove the following lines when you implement this test.
        $this->object->setAttempt('192.168.1.1');
        $this->object->setAttempt('192.168.1.1');
        $this->object->setAttempt('192.168.1.1');
        $this->object->setAttempt('192.168.1.1');
        $this->object->setAttempt('192.168.1.1');
        $this->object->setAttempt('192.168.1.1');
        $file = fopen('' . '/Cache/ip.list', 'rb');
        $line = explode(';', trim(fgets($file)));
        $this->assertNotEmpty($line);
    }

    /**
     * @covers FacturaScripts\Core\Base\IPFilter::isBanned
     * @todo   Implement testIsBanned().
     */
    public function testIsBanned() {
        // Remove the following lines when you implement this test.
        $this->assertTrue($this->object->isBanned('192.168.1.1'));
    }

}
