<?php

namespace FacturaScripts\Core\Base;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-21 at 11:14:25.
 */
class MiniLogTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var MiniLog
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MiniLog;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers FacturaScripts\Core\Base\MiniLog::emergency
     * @todo   Implement testEmergency().
     */
    public function testEmergency() {
        // Remove the following lines when you implement this test.
        $this->object->emergency('emergencia');
    }

    /**
     * @covers FacturaScripts\Core\Base\MiniLog::alert
     * @todo   Implement testAlert().
     */
    public function testAlert() {
        // Remove the following lines when you implement this test.
        $this->object->alert('alerta');
    }

    /**
     * @covers FacturaScripts\Core\Base\MiniLog::critical
     * @todo   Implement testCritical().
     */
    public function testCritical() {
        // Remove the following lines when you implement this test.
        $this->object->critical('critical');
    }

    /**
     * @covers FacturaScripts\Core\Base\MiniLog::error
     * @todo   Implement testError().
     */
    public function testError() {
        // Remove the following lines when you implement this test.
        $this->object->error('error');
    }

    /**
     * @covers FacturaScripts\Core\Base\MiniLog::warning
     * @todo   Implement testWarning().
     */
    public function testWarning() {
        // Remove the following lines when you implement this test.
        $this->object->warning('warning');
    }

    /**
     * @covers FacturaScripts\Core\Base\MiniLog::notice
     * @todo   Implement testNotice().
     */
    public function testNotice() {
        // Remove the following lines when you implement this test.
        $this->object->notice('notice');
    }

    /**
     * @covers FacturaScripts\Core\Base\MiniLog::info
     * @todo   Implement testInfo().
     */
    public function testInfo() {
        // Remove the following lines when you implement this test.
        $this->object->info('info');
    }

    /**
     * @covers FacturaScripts\Core\Base\MiniLog::debug
     * @todo   Implement testDebug().
     */
    public function testDebug() {
        // Remove the following lines when you implement this test.
        $this->object->debug('emdebug');
    }

    /**
     * @covers FacturaScripts\Core\Base\MiniLog::sql
     * @todo   Implement testSql().
     */
    public function testSql() {
        // Remove the following lines when you implement this test.
        
    }

    /**
     * @covers FacturaScripts\Core\Base\MiniLog::log
     * @todo   Implement testLog().
     */
    public function testLog() {
        // Remove the following lines when you implement this test.
        
    }

    /**
     * @covers FacturaScripts\Core\Base\MiniLog::read
     * @todo   Implement testRead().
     */
    public function testRead() {
        // Remove the following lines when you implement this test.
        // si se descomenta la linea inferior, se comprueba que el clear limpia el arrary y da error
        //$this->object->clear();
        $this->assertNotEmpty($this->object->read());
    }

}
