<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLprqxw4\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLprqxw4/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLprqxw4.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLprqxw4\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerLprqxw4\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Lprqxw4',
    'container.build_id' => 'f12421f0',
    'container.build_time' => 1517756906,
));
