name: Test Facturascripts

on:
  push:
    branches: [ "master", "githubActions" ]
  pull_request:
    branches: [ "master", "githubActions" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4'] # versiones no validas (phpunit)['5.6', '7.0', '7.1', '7.2', '7.3']

    name: Tests unitarios en PHP ${{ matrix.php-versions }}
    steps:
    - name: Agregar el repo
      uses: actions/checkout@v4

    - name: Instalar PHP ${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: bcmath, curl, gd, iconv, mysqli, pdo_mysql, soap, zip, fileinfo, openssl, simplexml, mbstring

    - name: Instalar dependencias
      uses: "ramsey/composer-install@v3"

    - name: Montar base de datos
      uses: shogo82148/actions-setup-mysql@v1
      with:
        distribution: "mysql"
        mysql-version: "8.0"
        root-password: "root"
      
    - name: Crear base de datos
      run: 'mysql -u root -proot -e "CREATE DATABASE facturascripts CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"'

    - name: Agregar configuración del proyecto
      run: echo "<?php
          define('FS_COOKIES_EXPIRE', 31536000);
          define('FS_ROUTE', '');
          define('FS_DB_TYPE', 'mysql');
          define('FS_DB_HOST', '127.0.0.1');
          define('FS_DB_PORT', 3306);
          define('FS_DB_NAME', 'facturascripts');
          define('FS_DB_USER', 'root');
          define('FS_DB_PASS', 'root');
          define('FS_DB_FOREIGN_KEYS', true);
          define('FS_DB_TYPE_CHECK', true);
          define('FS_MYSQL_CHARSET', 'utf8mb4');
          define('FS_MYSQL_COLLATE', 'utf8mb4_unicode_520_ci');
          define('FS_LANG', 'es_ES');
          define('FS_TIMEZONE', 'Europe/Madrid');
          define('FS_HIDDEN_PLUGINS', '');
          define('FS_DEBUG', true);
          define('FS_DISABLE_ADD_PLUGINS', false);
          define('FS_DISABLE_RM_PLUGINS', false);" > config.php

    - name: Ejecutar tests
      run: vendor/bin/phpunit --testdox --colors=always
